services:
  postgres:
    image: postgres:17.2
    container_name: postgres
    restart: always
    environment:
      TZ: America/Sao_Paulo
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: web
    ports:
      - "3000:3000"
    command: rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
      css:
        condition: service_started
    tty: true
    stdin_open: true

  css:
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    command: yarn watch:css
    volumes:
      - .:/app

volumes:
  rubygems:
  database:
